version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: anysoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - nestjs-network
    restart: unless-stopped
networks:
  nestjs-network:
